# Generated by Django 3.2.7 on 2021-09-08 06:18

import articles.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_article_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(upload_to=articles.models.articles_image_path),
        ),
    ]
